### ISSUE TITLE
[Bug] Gres  written incorrectly when using Node model and slurmconfig editor

### ISSUE THREAD

**Issue by dsloanm** [charmed-hpc/slurmutils#38]
### Bug Description

When using the `slurmconfig` editor with the `Node` model, Gres values are written out with commas separating each character of the string.

### To Reproduce

Running:

```python3
from slurmutils.editors import slurmconfig
from slurmutils.models import Node

with slurmconfig.edit("slurm.conf") as config:
    node = Node(
        NodeName="ip-172-31-38-11",
        Gres="gpu:tesla_t4:1",
    )
    config.nodes.update(node.dict())
```

produces `slurm.conf`:

`NodeName=ip-172-31-38-11 Gres=g,p,u,:,t,e,s,l,a,_,t,4,:,1`

rather than expected:

`NodeName=ip-172-31-38-11 Gres=gpu:tesla_t4:1`

### Environment

Running locally with the latest main commit: 60bc8e6.

### Relevant log output

```shell
N/A
```

**Comment by NucciTheBoss** [comment]
Taking a quick peak at this issue, it's a symptom of #34 where we don't have good type checking enabled. Gres can be a comma-delimited list, which means that it's a `list[str]` type rather than just `str`. Since there's no real type checking, `slurmutils` will happily try to marshal a value using the assigned callback even if the value is the incorrect type.

The `Gres` configuration option is assigned the `CommaSeparatorCallback` so the value for `Gres` must be passed as a list:

https://github.com/charmed-hpc/slurmutils/blob/60bc8e617d4745773995ea55288851bdee28ad6e/slurmutils/models/option.py#L437

The way to solve your issue here would be to pass the value of Gres as a `list[str]` rather than just a `str`:

```python3
from slurmutils.editors import slurmconfig
from slurmutils.models import Node

with slurmconfig.edit("slurm.conf") as config:
    node = Node(
        NodeName="ip-172-31-38-11",
        Gres=["gpu:tesla_t4:1"],
    )
    config.nodes.update(node.dict())
```

**Comment by dsloanm** [comment]
Can confirm using a list solves this.
